### ISSUE TITLE
Unable to access tvheadend.org website

### ISSUE THREAD

**Issue by kellerjustin** [tvheadend/tvheadend-documentation#15]
Not sure where to report this - I can't get to tvheadend.org. Tried on multiple different machines and locations, home, work, through verizon wireless, etc. Keep getting the same error.
![screenshot from 2019-02-21 09-59-41](https://user-images.githubusercontent.com/31552409/53182690-a08afe00-35bf-11e9-8465-e6d5dda20488.png)

New to tvheadend, coming from mythtv - would like to learn more about it but it's tough when the website is down -- thanks!

**Comment by mpmc** [comment]
I'm only speculating but I suspect the downtime is something to do with the runc security issue, or a pending upgrade is being done. We won't know more until @andoma has time to look at it, unfortunately he's very busy.

**Comment by kellerjustin** [comment]
working now - thanks!
@andoma @mpmc
